---
title: "RPackages"
author: "Irem YUCEL"
date: "02/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

--- R Functions ---
```{r}
library(dplyr)

fun <- function(data, col) {
  calculations <- dplyr::summarise(data,
                                    is.numeric_x = is.numeric({{col}}),
                                    class_x = class({{col}}))
  if (!calculations$is.numeric){
    stop("Selected column is not numeric. Column is:", calculations$class)
  }
  stopifnot()
  dplyr::select(data, col) # will try tp find "col" col in data, will not replace with the input col. Use double curly brackets.
}

##curly curly only works in dplyr - tidyverse functions. try to make it in tidyverse function!!

fun(gapminder, country)

fun2 <- function(data, calculation){
  dplyr::mutate(data, {{calculation}})
}

fun2(gapminder, as.factor(gdpPercap * pop))
```

R Packages

#devtools make changes to your PC within R

```{r}
#library(devtools)
#create.package("/Users/iremyucel/Desktop/powers")

#On the new Rstudio powers"
#library(devtools)
#use_git()

#' Square the input
#'
#'@param x Vector to square
#'@return The vector `x` squared
#'@examples
#'
#'square(1:10)
#'square(7)
#'@export
square <- function(x){
  x ^ 2
}

```











